### PR TITLE
Deno support: deno2node (2)

### PR DESCRIPTION
**Pull request by dcdunkan**
Deno support using [deno2node](https://github.com/fromdeno/deno2node).
Basically the same as #1 opened by roj1512.
- Formatted with Deno formatter.
- No deno lint errors were produced.

### CODE REVIEW

**Comment by slavafomin** [comment]
Hello! And thank you for your time. However, could you please look at my comment for the first PR that you've mentioned? It applies to your implementation as well.

**Comment by dcdunkan** [comment]
I've reverted the formatting. Now, it's just the changes in imports and exports. Is it good? Anything else?

**Comment by slavafomin** [comment]
Sorry, but it is still too invasive. Could you add Deno support without actually rewriting the code in Deno?

**Comment by dcdunkan** [comment]
[deno2node](https://github.com/fromdeno/deno2node) compiles Deno code to run on Node. So, if we are using deno2node for the Deno support, the codebase should be written in Deno; and then, deno2node can backport it to Node.

And as you can see in the commits, not much have been changed. Just the imports and exports, and NPM scripts.

If you don't want to change the codebase to Deno, I think, we might have to create a separate repository for Deno (I can do it, if you don't want to). But, I would recommend using deno2node, because, 1) it works, and 2) this library is a dependency of [your grammY plugin](https://github.com/grammyjs/fluent) which I'd like to have Deno support (grammY and its plugins use deno2node).

*There's another tool for this Node -> Deno purpose: [denoify](https://github.com/garronej/denoify), not sure whether it works well or not.

**Comment by slavafomin** [comment]
@dcdunkan thank you for clarification. This is exactly the point. I don't want to convert Node.js package to Deno. However, I'm not against adding the **Deno support** if community needs it. However, I want it in a most unobtrusive way as possible to the original code. If you have capacity to maintain the fork, I can only thank you for it, but if there are other less obtrusive solutions than `deno2node` I think they deserve an investigation, because it would be more maintainable than keeping a fork.

**Comment by dcdunkan** [comment]
I agree and thank you for the reply. And until we find a proper solution for this, if it helps the plugin, yes I think I can maintain a deno port fork. Should I close this PR?

(The plugin might also have to change to deno2node like the other plugins, is that a problem?)

**Comment by slavafomin** [comment]
Thank you. You can close the PR if you are not planning to work on it further. E.g. to study other options.
After creating a deno-compatible fork, feel free to add a link to it in the README of this package as well.

**Comment by dcdunkan** [comment]
Sure, I will. And I would like to look for other options. I'll close this PR later, if I stop looking for them. Thank you.

**Pull request closed without merging**
